name: Create Aries video

on:
  push:
    branches: master

jobs:
  call-workflow-1-in-local-repo:
    uses: ./.github/workflows/youtube-template.yml
    with:
      sign: aries
      api_url: ${{secrets.API_URL}}
      yt_email: ${{secrets.YT_EMAIL}}
      yt_password: ${{secrets.YT_PASSWORD}}
      affliate_link: ${{secrets.AFFLIATE_LINK}}
