name: Create Aries video

on:
  push:
    branches: master
env:
  API_URL: ${{secrets.API_URL}}
  YT_EMAIL: ${{secrets.YT_EMAIL}}
  YT_PASSWORD: ${{secrets.YT_PASSWORD}}
  AFFLIATE_LINK: ${{secrets.AFFLIATE_LINK}}

jobs:
  call-workflow-in-local-repo:
    uses: ./.github/workflows/youtube-template.yml
    with:
      sign: aries
      api_url: ${{env.API_URL}}
      yt_email: ${{env.YT_EMAIL}}
      yt_password: ${{env.YT_PASSWORD}}
      affliate_link: ${{env.AFFLIATE_LINK}}
