name: Create Aries video

on:
  push:
    branches: master
  schedule:
    - cron: "0 20 * * *" # Everyday at 20.00 UTC

jobs:
  call-workflow-in-local-repo:
    uses: ./.github/workflows/youtube-template.yml
    with:
      sign: aries
    secrets:
      API_URL: ${{secrets.API_URL}}
      YT_EMAIL: ${{secrets.YT_EMAIL}}
      YT_PASSWORD: ${{secrets.YT_PASSWORD}}
      AFFLIATE_LINK: ${{secrets.AFFLIATE_LINK}}
