name: Create cancer video

on:
  schedule:
    - cron: "30 21 * * *"

jobs:
  call-workflow-in-local-repo:
    uses: ./.github/workflows/youtube-template.yml
    with:
      sign: cancer
    secrets:
      API_URL: ${{secrets.API_URL}}
      YT_EMAIL: ${{secrets.YT_EMAIL}}
      YT_PASSWORD: ${{secrets.YT_PASSWORD}}
      AFFLIATE_LINK: ${{secrets.AFFLIATE_LINK}}
