name: Delete artifacts

on:
  workfow_dispatch:

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    needs: upload-videos-yt
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0days # Setting this to 0 will delete all artifacts
