name: Create youtube video
on:
  push:
    branches: master
env:
  frames_per_worker: 100

jobs:
  render-videos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        worker: [0]
        # worker: [0, 1, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - uses: actions/checkout@v2
      - uses: FedericoCarboni/setup-ffmpeg@v2

      - run: npm install remotion react react-dom @remotion/cli
      - run: |
          output=$(npx remotion render remotion/src/index.tsx Horoscope output/audio.mp3 --frames=0-50)
          value=$(echo "$output" | grep -oE '[0-9]+/[0-9]+' | awk -F '/' '{print $2}' | tail -n 1)
          echo "The value is: $value"

      # - run: echo "start=$((${{matrix.worker}}*${{env.frames_per_worker}}))" >> $GITHUB_ENV
      # - run: echo "end=$((${{matrix.worker}}*${{env.frames_per_worker}}+${{env.frames_per_worker}}-1))" >> $GITHUB_ENV

      # - run: npx remotion render remotion/src/index.tsx Horoscope output/${{matrix.worker}}.mp4 --frames=${{env.start}}-${{env.end}} --muted

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: output
      #     path: ./output
      #     retention-days: 1
