name: Create youtube video
on:
  push:
    branches: master

jobs:
  render-videos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        worker: [0]
        # worker: [0, 1, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - uses: actions/checkout@v2
      - uses: FedericoCarboni/setup-ffmpeg@v2

      - run: npm install remotion react react-dom @remotion/cli

      - name: Render audio & Get total frames
      - run: |
          output=$(npx remotion render remotion/src/index.tsx Horoscope output/audio.mp3 --frames=0-50)
          value=$(echo "$output" | grep -oE '[0-9]+/[0-9]+' | awk -F '/' '{if ($1 == $2 && $1 > 3) print $1}' | tail -n 1)
          echo "total_frames=$value" >> $GITHUB_ENV

      # - name: Set frames per worker
      #   run: |
      #     framesPerWorker=$((${{env.total_frames}}/${{worker.length}}))
      #     echo "frames_per_worker=$framesPerWorker" >> $GITHUB_ENV

      # - name: Set start frame
      #   run: echo "start=$((${{matrix.worker}}*${{env.frames_per_worker}}))" >> $GITHUB_ENV

      # - name: Set end frame
      #   run: |
      #     if [ "$matrix.worker" -lt ${{matrix.length}} - 1 ]; then
      #       echo "end=$((${{matrix.worker}}*${{env.frames_per_worker}}+${{env.frames_per_worker}}-1))" >> $GITHUB_ENV
      #     else
      #       echo "end=${{env.total_frames}}" >> $GITHUB_ENV
      #     fi

      # - run: echo ${{start}} ${{end}}

      # - run: npx remotion render remotion/src/index.tsx Horoscope output/${{matrix.worker}}.mp4 --frames=${{env.start}}-${{env.end}} --muted

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: output
      #     path: ./output
      #     retention-days: 1
