name: Create youtube video
on:
  push:
    branches: master

env:
  NUM_OF_WORKERS: 1

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    steps:
      - id: set-matrix
        run: |
          array=($(for i in $(seq 1 3); do echo "$i"; done))
          echo 'version_matrix=${array[@]}' >> $GITHUB_OUTPUT
    outputs:
      version_matrix: ${{ steps.set-matrix.outputs.version_matrix }}

  render-video:
    runs-on: ubuntu-latest
    needs: build-matrix
    strategy:
      matrix:
        worker_id: ${{ fromJson(needs.build-matrix.outputs.version_matrix) }}
    steps:
      - run: echo ${{matrix.worker_id}}
        # - uses: actions/checkout@v2
        # - uses: FedericoCarboni/setup-ffmpeg@v2

        # - run: npm install remotion react react-dom @remotion/cli

        # - name: Render audio & Get total frames
        #   run: |
        #     output=$(npx remotion render remotion/src/index.tsx Horoscope output/audio.mp3 --frames=0-10)
        #     value=$(echo "$output" | grep -oE '[0-9]+/[0-9]+' | awk -F '/' '{if ($1 == $2 && $1 > 3) print $1}' | tail -n 1)
        #     echo "total_frames=$value" >> $GITHUB_ENV

        # - name: Set frames per worker
        #   run: |
        #     framesPerWorker=$((${{env.total_frames}}/${{matrix.worker.length}}))
        #     echo "frames_per_worker=$framesPerWorker" >> $GITHUB_ENV

        # - run: echo ${{env.total_frames}} ${{env.frames_per_worker}}

        # - name: Set start frame
        #   run: echo "start=$((${{matrix.worker}}*${{env.frames_per_worker}}))" >> $GITHUB_ENV

        # - name: Set end frame
        #   run: |
        #     if [ "$matrix.worker" -lt ${{matrix.length}} - 1 ]; then
        #       echo "end=$((${{matrix.worker}}*${{env.frames_per_worker}}+${{env.frames_per_worker}}-1))" >> $GITHUB_ENV
        #     else
        #       echo "end=${{env.total_frames}}" >> $GITHUB_ENV
        #     fi

        # - run: echo ${{start}} ${{end}}

        # - run: npx remotion render remotion/src/index.tsx Horoscope output/${{matrix.worker}}.mp4 --frames=${{env.start}}-${{env.end}} --muted

        # - uses: actions/upload-artifact@v3
        #   with:
        #     name: output
        #     path: ./output
        #     retention-days: 1
