name: Reusable
on:
  workflow_call:
    inputs:
      num_of_workers:
        required: true
        type: number
      remotion_entry_point:
        required: true
        type: string
      remotion_composition_id:
        required: true
        type: string
      output_path:
        required: true
        type: string

env:
  REMOTION_ENTRY_POINT: ${{inputs.remotion_entry_point}}
  REMOTION_COMPOSITION_ID: ${{inputs.remotion_composition_id}}
  NUM_OF_WORKERS: ${{inputs.num_of_workers}}
  OUTPUT_PATH: ${{inputs.output_path}}

jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p $(dirname ${{env.OUTPUT_PATH}})
      - run: touch "${{env.OUTPUT_PATH}}"

      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./output
