name: Reusable
on:
  workflow_call:
    inputs:
      num_of_workers:
        required: true
        type: number
      remotion_entry_point:
        required: true
        type: string
      remotion_composition_id:
        required: true
        type: string
      output_dir:
        required: true
        type: string
      sign:
        required: true
        type: string

env:
  REMOTION_ENTRY_POINT: ${{inputs.remotion_entry_point}}
  REMOTION_COMPOSITION_ID: ${{inputs.remotion_composition_id}}
  NUM_OF_WORKERS: ${{inputs.num_of_workers}}
  OUTPUT_DIR: ${{inputs.output_dir}}
  SIGN: ${{inputs.sign}}

jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir ${{env.OUTPUT_DIR}} && cd ${{env.OUTPUT_DIR}}
      - run: touch "${{env.SIGN}}.txt"

      - uses: actions/upload-artifact@v3
        with:
          name: ${{env.OUTPUT_DIR}}
          path: ${{env.OUTPUT_DIR}}
