name: Create scorpio video

on:
  schedule:
    - cron: "30 23 * * *"

jobs:
  call-workflow-in-local-repo:
    uses: ./.github/workflows/youtube-template.yml
    with:
      sign: scorpio
    secrets:
      API_URL: ${{secrets.API_URL}}
      YT_EMAIL: ${{secrets.YT_EMAIL}}
      YT_PASSWORD: ${{secrets.YT_PASSWORD}}
      AFFLIATE_LINK: ${{secrets.AFFLIATE_LINK}}
