name: Test

on:
  push:
    branches: master

jobs:
  job1:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix: ${{fromJson(needs.job1.outputs.package.outputs.content)}}
    steps:
      - uses: actions/checkout@main

      # - name: JSON to variables
      #   uses: antifree/json-to-variables@v1.0.1
      #   with:
      #     filename: "signs.json"
      #     prefix: json

      # - name: Show output
      #   run: echo ${{ env.json_include }}

      - run: file_contents=$(cat signs.json)
      - run: echo $file_contents
