name: Caching with npm
on: push

jobs:
  cache-node-modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ hashFiles('**/package-lock.json') }}

      - run: npm ci

  check:
    runs-on: ubuntu-latest
    needs: cache-node-modules
    steps:
      - uses: actions/checkout@v3

      - name: Restore node modules cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ hashFiles('**/package-lock.json') }}

      - run: npm run build
