name: Test

on:
  push:
    branches: master
  # workflow_dispatch:

jobs:
  call-workflow-in-local-repo:
    uses: ./.github/workflows/reusable.yml
    with:
      num_of_workers: 2
      remotion_composition_id: Horoscope
      remotion_entry_point: remotion/src/index.tsx
      output_path: aries.txt
