name: Test

on:
  push:
    branches: master
  # workflow_dispatch:

jobs:
  call-workflow-in-local-repo:
    uses: ./.github/workflows/reusable.yml
    with:
      num_of_workers: 2
      remotion_composition_id: Horoscope
      remotion_entry_point: remotion/src/index.tsx
      output_dir: output
      sign: aries

  check-artifact:
    runs-on: ubuntu-latest
    needs: call-workflow-in-local-repo
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - run: cd output && ls
