name: Caching with npm
on: push

jobs:
  cache-node-modules-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            build
          key: ${{ hashFiles('**/package-lock.json') }}

      - run: npm install
      - run: npm run build

  check:
    runs-on: ubuntu-latest
    needs: cache-node-modules-and-build
    steps:
      - uses: actions/checkout@v3

        uses: actions/cache@v3
        with:
          path: |
            node_modules
            build
          key: ${{ hashFiles('**/package-lock.json') }}
      
      - run: node build/server/scrape_horoscopes.js