name: Create youtube video
env:
  HOROSCOPE_API_URL: ${{secrets.HOROSCOPE_API_URL}}
  VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}

on:
  push:
    branches: master

jobs:
  scrape-horoscopes:
    name: Scrape Horsocope
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: npm run install-build
      - run: node build/server/scrape_horoscopes.js
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./output
          retention-days: 1

  generate-tts-1:
    runs-on: ubuntu-latest
    needs: scrape-horoscopes
    strategy:
      matrix:
        sign: ["aries", "taurus", "gemini", "cancer", "leo", "virgo"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg
      - run: npm run install-build
      - run: node build/server/generate_tts.js ${{ matrix.sign }}
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./output
          retention-days: 1

  generate-tts-2:
    runs-on: ubuntu-latest
    needs: generate-tts-1
    strategy:
      matrix:
        sign:
          ["libra", "scorpio", "sagittarius", "capricorn", "aquarius", "pisces"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg
      - run: npm run install-build
      - run: node build/server/generate_tts.js ${{ matrix.sign }}
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./output
          retention-days: 1

  generate-subtitles:
    runs-on: ubuntu-latest
    needs: generate-tts-2
    strategy:
      matrix:
        sign:
          [
            "aries",
            "taurus",
            "gemini",
            "cancer",
            "leo",
            "virgo",
            "libra",
            "scorpio",
            "sagittarius",
            "capricorn",
            "aquarius",
            "pisces",
          ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
      - run: npm run install-build
      - run: node build/server/generate_subtitles.js ${{ matrix.sign }}
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./output
          retention-days: 1

  merge-subtitles:
    runs-on: ubuntu-latest
    needs: generate-subtitles
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
      - run: npm run install-build
      - run: node build/server/merge_subtitles.js
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./output
          retention-days: 1

  generate-images:
    runs-on: ubuntu-latest
    needs: merge-subtitles
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
      - run: npm run install-build
      - run: node build/server/generate_img.js
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./output
          retention-days: 1
