name: Create youtube video
env:
  HOROSCOPE_API_URL: ${{secrets.HOROSCOPE_API_URL}}
  PICTORY_REFRESH_TOKEN: ${{secrets.PICTORY_REFRESH_TOKEN}}
  PICTORY_CLIENT_ID: ${{secrets.PICTORY_CLIENT_ID}}

on:
  push:
    branches: master

jobs:
  scrape-horoscopes:
    name: Scrape Horsocope
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: npm run install-build
      - run: node build/server/scrape_horoscopes.js
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./output
          retention-days: 1

  generate-tts:
    runs-on: ubuntu-latest
    needs: scrape-horoscopes
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
      - run: npm run install-build
      - run: node build/server/generate_tts.js
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./output
          retention-days: 1

  generate-subtitles:
    runs-on: ubuntu-latest
    needs: generate-tts
    strategy:
      matrix:
        sign: ["aries"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
      - run: npm run install-build
      - run: node build/server/generate_subtitles.js ${{ matrix.sign }}
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./output
          retention-days: 1

  generate-images-1:
    runs-on: ubuntu-latest
    needs: generate-subtitles
    strategy:
      matrix:
        sign: ["aries"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
      - run: npm run install-build
      - run: node build/server/generate_img.js ${{ matrix.sign }}
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./output
          retention-days: 1

  # generate-images-2:
  #   runs-on: ubuntu-latest
  #   needs: generate-images-1
  #   strategy:
  #     matrix:
  #       sign:
  #         ["libra", "scorpio", "sagittarius", "capricorn", "aquarius", "pisces"]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/download-artifact@v3
  #     - run: npm run install-build
  #     - run: node build/server/generate_img.js ${{ matrix.sign }}
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: output
  #         path: ./output
  #         retention-days: 1

  render-videos:
    runs-on: ubuntu-latest
    needs: generate-images-1
    strategy:
      matrix:
        sign: ["aries"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
      # - uses: dawidd6/action-download-artifact@v2
      #   with:
      #     run_id: 4042410763
      - run: npm install remotion react react-dom @remotion/cli
      - run: npx remotion render remotion/src/index.tsx  Horoscope output/${{matrix.sign}}.mp4 --props="{\"sign\":\"${{matrix.sign}}\"}"
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./output
          retention-days: 1
