name: Create youtube video
env:
  API_URL: ${{secrets.API_URL}}
  YT_EMAIL: ${{secrets.YT_EMAIL}}
  YT_PASSWORD: ${{secrets.YT_PASSWORD}}
  AFFLIATE_LINK: ${{secrets.AFFLIATE_LINK}}

on:
  push:
    branches: master

jobs:
  scrape-horoscopes:
    name: Scrape Horsocope
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: npm run install-build
      - run: node build/server/scrape_horoscopes.js
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./output
          retention-days: 1

  generate-tts:
    runs-on: ubuntu-latest
    needs: scrape-horoscopes
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - run: npm run install-build
      - run: node build/server/generate_tts.js
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./output
          retention-days: 1

  generate-subtitles-and-get-videos-urls:
    runs-on: ubuntu-latest
    needs: generate-tts
    strategy:
      matrix:
        sign:
          [
            "aries",
            "taurus",
            "gemini",
            "cancer",
            "leo",
            "virgo",
            "libra",
            "scorpio",
            "sagittarius",
            "capricorn",
            "aquarius",
            "pisces",
          ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - run: npm run install-build
      - run: node build/server/generate_subtitles_videos.js ${{ matrix.sign }}
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./output
          retention-days: 1

  render-videos:
    needs: generate-subtitles-and-get-videos-urls
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sign:
          [
            "aries",
            "taurus",
            "gemini",
            "cancer",
            "leo",
            "virgo",
            "libra",
            "scorpio",
            "sagittarius",
            "capricorn",
            "aquarius",
            "pisces",
          ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - uses: FedericoCarboni/setup-ffmpeg@v2

      - run: npm install remotion react react-dom @remotion/cli
      - run: npx remotion render remotion/src/index.tsx  Horoscope output/videos/${{matrix.sign}}.mp4 --props="{\"sign\":\"${{matrix.sign}}\"}"
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./output
          retention-days: 1
    # uses: ./.github/workflows/render-matrix.yml
    # with:
    #   num_of_workers: 50
    #   remotion_composition_id: Horoscope
    #   remotion_entry_point: remotion/src/index.tsx
    #   output_path: output/videos/${{matrix.sign}}.mp4
    #   sign: ${{matrix.sign}}

  upload-videos-yt:
    runs-on: ubuntu-latest
    needs: render-videos
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - run: npm run install-build
      - run: node build/server/generate_thumbnails.js
      - run: node build/server/generate_tags.js
      - run: node build/server/upload_yt.js

  delete-artifacts: upload-videos-yt
    runs-on: ubuntu-latest
    needs: 
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0days # Setting this to 0 will delete all artifacts
