name: Create youtube video
env:
  HOROSCOPE_API_URL: ${{secrets.HOROSCOPE_API_URL}}

on:
  push:
    branches: master
  # schedule:
  #   - cron: "0 15 * * *"
jobs:
  scrape-horoscopes:
    name: Scrape Horsocope
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - run: npm install
      - run: npm run scrape-horoscope

      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./output
          retention-days: 1

  generate-tts:
    runs-on: ubuntu-latest
    needs: scrape-horoscopes
    # strategy:
    #   matrix:
    #     sign: ["aries", "pisces", "cancer"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
      - run: sudo apt install ffmpeg
      - run: npm install
      - run: npm run build
      - run: node build/server/generate_tts.js pisces
      - run: ls
      - run: cd output && ls
      # - run: node build/server/generate_tts.js ${{ matrix.sign }}
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./output
          retention-days: 1
