name: Create youtube video
env:
  HOROSCOPE_API_URL: ${{secrets.HOROSCOPE_API_URL}}

on:
  push:
    branches: master
  # schedule:
  #   - cron: "0 15 * * *"

jobs:
  scrape-horoscopes:
    name: Scrape Horsocope
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - run: npm install
      - run: npm run scrape-horoscope

      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./output
          retention-days: 1

  generate-tts:
    runs-on: ubuntu-latest
    needs: scrape-horoscopes
    strategy:
      matrix:
        sign:
          [
            "aries",
            "taurus",
            "gemini",
            "cancer",
            "leo",
            "virgo",
            "libra",
            "scorpio",
            "sagittarius",
            "capricorn",
            "aquarius",
            "pisces",
          ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
      # - run: sudo apt install ffmpeg
      - uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg
      - run: npm install
      - run: npm run build
      - run: node build/server/generate_tts.js ${{ matrix.sign }}
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./output
          retention-days: 1

  generate-ai-images:
    runs-on: ubuntu-latest
    needs: generate-tts
    strategy:
      matrix:
        sign:
          [
            "aries",
            "taurus",
            "gemini",
            "cancer",
            "leo",
            "virgo",
            "libra",
            "scorpio",
            "sagittarius",
            "capricorn",
            "aquarius",
            "pisces",
          ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
      - run: npm install
      - run: npm run build
      - run: node build/server/generate_img.js ${{ matrix.sign }}
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: ./output
          retention-days: 1
